import { useEffect, useMemo, useRef, useState, type ReactNode } from "react";
import { motion, AnimatePresence } from "framer-motion";
import "leaflet/dist/leaflet.css";
import { CircleMarker, MapContainer, Marker, Polygon, Popup, TileLayer, useMap } from "react-leaflet";
import { divIcon, type LatLngExpression } from "leaflet";
import { ArrowUpRight, BusFront, Check, ChevronDown, CircleHelp, Download, Droplets, Factory, Gauge, GitCompareArrows, History, Home as HomeIcon, Layers3, Leaf, MapPin, Printer, Search, ShieldCheck, Sun, Trees, TreePine, Umbrella, Waves, Wind, X, Zap } from "lucide-react";
import { toast } from "sonner";

type CityKey = "Chennai" | "Bengaluru" | "Delhi";
type City = { city: string; state: string; lat: number; lon: number; temp: number; surface: number; utci: number; zone: string; humidity?: number; primaryHeatDrivers?: string[]; isFallback?: boolean };
const cityData: Record<CityKey, City> = {
  Chennai: { city: "Chennai", state: "Tamil Nadu", lat: 13.0827, lon: 80.2707, temp: 34.8, surface: 48.2, utci: 42.6, zone: "T. Nagar / Central Chennai" },
  Bengaluru: { city: "Bengaluru", state: "Karnataka", lat: 12.9716, lon: 77.5946, temp: 28.4, surface: 38.1, utci: 32.2, zone: "Koramangala / South Bengaluru" },
  Delhi: { city: "Delhi", state: "Delhi NCR", lat: 28.6139, lon: 77.209, temp: 41.2, surface: 53.6, utci: 47.1, zone: "Lajpat Nagar / South Delhi" },
};
const cityKeys = Object.keys(cityData) as CityKey[];

function Ticker({ value, decimals = 1, prefix = "", suffix = "" }: { value: number; decimals?: number; prefix?: string; suffix?: string }) {
  const [current, setCurrent] = useState(value);
  useEffect(() => { const start = performance.now(); const from = current; let frame = 0; const run = (now: number) => { const p = Math.min(1, (now - start) / 420); const ease = 1 - Math.pow(1 - p, 3); setCurrent(from + (value - from) * ease); if (p < 1) frame = requestAnimationFrame(run); }; frame = requestAnimationFrame(run); return () => cancelAnimationFrame(frame); }, [value]);
  return <>{prefix}{current.toFixed(decimals)}{suffix}</>;
}

function Card({ children, className = "", style }: { children: ReactNode; className?: string; style?: React.CSSProperties }) { return <motion.section className={`paper-card ${className}`} style={style} initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .45 }}>{children}</motion.section>; }
function Kicker({ children }: { children: ReactNode }) { return <div className="kicker"><span />{children}</div>; }

function QuenchLoader({ onDone }: { onDone: () => void }) {
  const [temp, setTemp] = useState(48.2);
  useEffect(() => { const started = performance.now(); const timer = window.setTimeout(onDone, 2500); let frame = 0; const tick = (now: number) => { const p = Math.min(1, (now - started) / 2200); setTemp(48.2 - 16.2 * (1 - Math.pow(1 - p, 2.4))); if (p < 1) frame = requestAnimationFrame(tick); }; frame = requestAnimationFrame(tick); return () => { window.clearTimeout(timer); cancelAnimationFrame(frame); }; }, [onDone]);
  return <motion.div className="quench" initial={{ opacity: 1 }} animate={{ opacity: 1 }} exit={{ y: "-100%" }} transition={{ duration: .7, ease: [0.77, 0, .175, 1] }}><div className="quench-wash" /><div className="quench-core"><div className="quench-brand">HEATSCAPE / THERMAL QUENCH</div><div className="quench-gauge"><div className="gauge-orbit orbit-a" /><div className="gauge-orbit orbit-b" /><Leaf size={48} className="quench-leaf" /><strong><Ticker value={temp} suffix="°C" /></strong></div><p>{temp > 32.1 ? "Critical Urban Heat" : "Thermal Equilibrium"}</p><div className="quench-line"><span style={{ width: `${((48.2 - temp) / 16.2) * 100}%` }} /></div><small>COOLING WAVE / MUNICIPAL THERMODYNAMICS</small></div></motion.div>;
}

function MapFocus({ city }: { city: City }) {
  const map = useMap();
  useEffect(() => { map.flyTo([city.lat, city.lon], 12, { duration: 1.2 }); }, [city, map]);
  return null;
}

const hotspotIcon = divIcon({ className: "heat-marker", html: '<span></span>' });

const riskOffsets = [[[-0.028,-0.035],[-0.006,-0.045],[0.012,-0.018],[0.004,0.014],[-0.02,0.01]], [[0.018,-0.018],[0.043,-0.004],[0.035,0.03],[0.004,0.023],[-0.01,0.0]], [[-0.018,0.018],[0.004,0.035],[0.025,0.018],[0.012,-0.008],[-0.012,-0.006]]];
function RiskLayer({ city }: { city: City }) { return <>{riskOffsets.map((offsets, index) => <Polygon key={index} positions={offsets.map(([lat, lon]) => [city.lat + lat, city.lon + lon] as LatLngExpression)} pathOptions={{ color: index === 1 ? "#ea580c" : "#c2410c", weight: 1.5, opacity: .65, fillColor: "#c2410c", fillOpacity: .13 }}><Popup><strong>Heat-risk ward {index + 1}</strong><br />Projected surface hotspot / {city.city}</Popup></Polygon>)}</>; }
function StreetMap({ city, onPick, showRisk }: { city: City; onPick: (key: CityKey) => void; showRisk: boolean }) {
  const center: LatLngExpression = [city.lat, city.lon];
  return <div className="street-map"><MapContainer center={center} zoom={12} scrollWheelZoom className="leaflet-map"><TileLayer url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png" attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>' /><MapFocus city={city} />{showRisk && <RiskLayer city={city} />}<CircleMarker center={center} radius={95} pathOptions={{ color: "#c2410c", weight: 1, opacity: .28, fillColor: "#c2410c", fillOpacity: .06 }} /><Marker position={center} icon={hotspotIcon}><Popup><strong>{city.city} hotspot</strong><br />Surface temperature {city.surface.toFixed(1)}°C</Popup></Marker>{cityKeys.filter((key) => key !== city.city).map((key) => <CircleMarker key={key} center={[cityData[key].lat, cityData[key].lon]} radius={6} pathOptions={{ color: "#c2410c", fillColor: "#c2410c", fillOpacity: .85 }} eventHandlers={{ click: () => onPick(key) }} />)}</MapContainer><div className="map-label"><span className="hot-dot" />{city.city.toUpperCase()} / LIVE HOTSPOT FOCUS <b>{city.lat.toFixed(4)}°N&nbsp; {city.lon.toFixed(4)}°E</b></div></div>;
}
function Toggle({ label, hint, checked, onChange, icon }: { label: string; hint: string; checked: boolean; onChange: () => void; icon: ReactNode }) { return <button className={`light-toggle ${checked ? "checked" : ""}`} onClick={onChange}><span className="toggle-icon">{icon}</span><span><b>{label}</b><small>{hint}</small></span><i><em /></i></button>; }
function Plan({ letter, title, subtitle, color, drop, roi, payback, emissions, icon, featured = false }: { letter: string; title: string; subtitle: string; color: string; drop: number; roi: number; payback: number; emissions: number; icon: ReactNode; featured?: boolean }) { return <motion.article className={`plan-light ${featured ? "featured-plan" : ""}`} style={{ "--plan": color } as React.CSSProperties} whileHover={{ y: -5 }}><div className="plan-light-top"><span>{letter}</span><b>{featured ? "RECOMMENDED MUNICIPAL TENDER" : "OPTIMIZED SCENARIO"}</b><ArrowUpRight size={15} /></div><div className="plan-light-icon">{icon}</div><h3>{title}</h3><p>{subtitle}</p><div className="plan-grid"><div><strong>−<Ticker value={drop} suffix="°C" /></strong><span>UTCI DROP</span></div><div><strong>+<Ticker value={roi} suffix="%" /></strong><span>5-YR ROI</span></div><div><strong><Ticker value={payback} suffix=" YRS" /></strong><span>PAYBACK</span></div><div><strong>−<Ticker value={emissions} decimals={0} suffix=" t" /></strong><span>NET CO2E REDUCED</span></div></div></motion.article>; }

function ComparisonModal({ calc, city, onClose }: { calc: any; city: City; onClose: () => void }) { const rows = [["UTCI DROP", `−${calc.planA.toFixed(1)}°C`, `−${calc.planB.toFixed(1)}°C`], ["5-YR ROI", `+${calc.aRoi.toFixed(1)}%`, `+${calc.bRoi.toFixed(1)}%`], ["PAYBACK", `${(3.8 - calc.lakhs * .025).toFixed(1)} YRS`, "4.5 YRS"], ["NET CO2E", `−${Math.round(270 + calc.lakhs * 13)} t`, `−${Math.round(400 + calc.lakhs * 15)} t`]]; return <motion.div className="feature-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.div className="comparison-sheet" initial={{ y: 20 }} animate={{ y: 0 }}><button className="paper-close" onClick={onClose}><X size={17} /></button><Kicker>SCENARIO COMPARISON / {city.city.toUpperCase()}</Kicker><h2>Plan A vs Plan B</h2><p>Evaluate cooling intensity against long-term ecological return for the active municipal zone.</p><div className="comparison-head"><div>METRIC</div><strong className="lapis">A / MAXIMUM COOLING</strong><strong className="sage">B / ECO-FORESTRY</strong></div>{rows.map(([label, a, b]) => <div className="comparison-row" key={label}><span>{label}</span><b>{a}</b><b>{b}</b></div>)}<div className="comparison-note"><Droplets size={16} /> Plan A prioritizes immediate thermal relief; Plan B compounds canopy and emissions benefits over a longer horizon.</div></motion.div></motion.div>; }
function SavedDrawer({ scenarios, onClose, onLoad }: { scenarios: any[]; onClose: () => void; onLoad: (scenario: any) => void }) { return <motion.aside className="saved-drawer" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }}><div className="drawer-head"><div><Kicker>SAVED SCENARIOS</Kicker><h2>BoQ tender history</h2></div><button onClick={onClose}><X size={17} /></button></div>{scenarios.length === 0 ? <div className="drawer-empty"><History size={28} /><b>No saved tenders yet</b><span>Export a municipal tender to keep a quick session copy here.</span></div> : <div className="scenario-list">{scenarios.map((scenario) => <button className="scenario-item" key={scenario.id} onClick={() => onLoad(scenario)}><span><b>{scenario.city}</b><small>{scenario.zone}</small></span><strong>₹{scenario.budget.toFixed(1)}L</strong><small>{scenario.savedAt}</small></button>)}</div>}</motion.aside>; }
function AuditDrawer({ logs, onClose }: { logs: any[]; onClose: () => void }) { return <motion.aside className="saved-drawer" initial={{ x: "100%" }} animate={{ x: 0 }} exit={{ x: "100%" }}><div className="drawer-head"><div><Kicker>SYSTEM AUDIT</Kicker><h2>Fallback Event History</h2></div><button onClick={onClose}><X size={17} /></button></div>{logs.length === 0 ? <div className="drawer-empty"><ShieldCheck size={28} /><b>No fallback events</b><span>System has maintained 100% API uptime.</span></div> : <div className="scenario-list" style={{ overflowY: "auto", maxHeight: "calc(100vh - 120px)" }}>{logs.map((log) => <div className="scenario-item" key={log.id} style={{ cursor: "default", gridTemplateColumns: "1fr" }}><span><b>{log.event || "API FALLBACK"}</b><small>{log.message}</small></span><small>{log.time}</small><pre style={{ fontSize: 9, color: "var(--smoke)", margin: 0, overflowX: "hidden", textOverflow: "ellipsis" }}>{JSON.stringify(log.payload)}</pre></div>)}</div>}</motion.aside>; }

const hotspotData = [
  { id: "industrial", name: "Industrial Zone", type: "Kilpauk industrial belt", peak: 52.4, risk: "Critical", offset: [0.012, 0.018], icon: Factory },
  { id: "residential", name: "High-Density Residential", type: "T. Nagar core", peak: 49.8, risk: "High", offset: [-0.01, -0.012], icon: HomeIcon },
  { id: "transit", name: "Transit Hub", type: "Central bus corridor", peak: 51.1, risk: "Critical", offset: [0.022, -0.02], icon: BusFront },
];
function HotspotFocus({ point, base }: { point: [number, number]; base: City }) { const map = useMap(); useEffect(() => { map.flyTo(point, 14, { duration: .9 }); }, [point, map]); return null; }
function HotspotsView({ city }: { city: City }) { const [selected, setSelected] = useState(hotspotData[0]); const pointFor = (spot: typeof hotspotData[number]) => [city.lat + spot.offset[0], city.lon + spot.offset[1]] as [number, number]; const activePoint = pointFor(selected); return <div className="feature-view dark-view"><div className="feature-view-head"><div><Kicker>HISTORICAL THERMAL INTELLIGENCE</Kicker><h1>Hotspots around {city.city}.</h1><p>Historical surface-temperature signals ranked by exposure, intensity, and municipal response urgency.</p></div><span className="dark-status"><i /> LANDSAT / 2019—2025</span></div><div className="hotspot-layout"><div className="hotspot-map"><MapContainer center={activePoint} zoom={13} className="feature-leaflet"><TileLayer url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}.png" attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>' /><HotspotFocus point={activePoint} base={city} />{hotspotData.map((spot) => { const point = pointFor(spot); return <CircleMarker key={spot.id} center={point} radius={spot.id === selected.id ? 18 : 11} pathOptions={{ color: spot.risk === "Critical" ? "#f97316" : "#fb923c", weight: 3, fillColor: "#ef4444", fillOpacity: .58 }} eventHandlers={{ click: () => setSelected(spot) }}><Popup><strong>{spot.name}</strong><br />Peak surface temperature: {spot.peak}°C</Popup></CircleMarker>; })}</MapContainer><div className="dark-map-caption"><span className="pulse-red" /> 3 THERMAL CLUSTERS / {city.city.toUpperCase()} <b>CLICK A MARKER TO INSPECT</b></div></div><aside className="hotspot-sidebar"><div className="sidebar-kicker"><Kicker>RISK REGISTER</Kicker><span>03 ZONES</span></div>{hotspotData.map((spot) => { const Icon = spot.icon; return <button key={spot.id} className={`hotspot-card ${selected.id === spot.id ? "selected" : ""}`} onClick={() => setSelected(spot)}><span className="spot-icon"><Icon size={18} /></span><span><b>{spot.name}</b><small>{spot.type}</small></span><strong>{spot.peak.toFixed(1)}°C<em className={spot.risk === "Critical" ? "critical" : "high"}>{spot.risk}</em></strong></button>; })}<div className="risk-summary"><span>AVERAGE PEAK</span><b>{(hotspotData.reduce((sum, item) => sum + item.peak, 0) / hotspotData.length).toFixed(1)}°C</b><small>+{(hotspotData.reduce((sum, item) => sum + item.peak, 0) / hotspotData.length - city.temp).toFixed(1)}° ABOVE AMBIENT</small></div></aside></div></div>; }
function InterventionsView() { const [added, setAdded] = useState<string[]>([]); const catalog = [{ id: "roof", title: "High-Albedo Cool Roofs", detail: "Reflective mineral coating", unit: "₹150 / sq.m", cooling: "−2.5°C localized drop", horizon: "Low", icon: Sun, color: "cyan" }, { id: "canopy", title: "Native Urban Canopy", detail: "Heat-resilient shade trees", unit: "₹1,400 / tree", cooling: "−3.8°C localized drop", horizon: "Medium", icon: TreePine, color: "green" }, { id: "bioswale", title: "Permeable Bioswales", detail: "Stormwater + evapotranspiration", unit: "₹2,200 / linear m", cooling: "−1.9°C localized drop", horizon: "Medium", icon: Waves, color: "blue" }, { id: "shade", title: "Tensile Shade Sails", detail: "Rapid pedestrian cover", unit: "₹3,800 / sq.m", cooling: "−2.1°C localized drop", horizon: "High", icon: Umbrella, color: "amber" }]; const toggle = (id: string) => setAdded((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); return <div className="feature-view dark-view"><div className="feature-view-head"><div><Kicker>COOLING TECHNOLOGY CATALOG</Kicker><h1>Interventions, made tangible.</h1><p>Build a custom municipal cooling stack from proven materials, canopy systems, and fast-deployment shade infrastructure.</p></div><span className="dark-status"><i /> {added.length} ADDED TO PLAN</span></div><div className="catalog-grid">{catalog.map((item) => { const Icon = item.icon; const isAdded = added.includes(item.id); return <article className={`catalog-card ${item.color} ${isAdded ? "added" : ""}`} key={item.id}><div className="catalog-top"><span className="catalog-icon"><Icon size={22} /></span><span className="catalog-tag">{item.horizon} MAINTENANCE</span></div><h2>{item.title}</h2><p>{item.detail}</p><div className="catalog-specs"><div><span>COST PER UNIT</span><b>{item.unit}</b></div><div><span>COOLING POTENTIAL</span><b>{item.cooling}</b></div><div><span>MAINTENANCE HORIZON</span><b>{item.horizon}</b></div></div><button className="catalog-toggle" onClick={() => toggle(item.id)}>{isAdded ? <><Check size={15} /> ADDED TO CUSTOM PLAN</> : <>ADD TO CUSTOM PLAN <ArrowUpRight size={15} /></>}</button></article>; })}</div></div>; }

export default function Home() {
  const [activeTab, setActiveTab] = useState<"planner" | "hotspots" | "interventions">("planner"); const [loading, setLoading] = useState(true); const [cityKey, setCityKey] = useState<CityKey>("Chennai"); const [activeCity, setActiveCity] = useState<City>(cityData.Chennai); const [query, setQuery] = useState("Chennai"); const [budget, setBudget] = useState(2700000); const [utilities, setUtilities] = useState(false); const [transit, setTransit] = useState(true); const [tenderOpen, setTenderOpen] = useState(false); const [compareOpen, setCompareOpen] = useState(false); const [savedOpen, setSavedOpen] = useState(false); const [auditOpen, setAuditOpen] = useState(false); const [showRisk, setShowRisk] = useState(false); const [suggestions, setSuggestions] = useState<any[]>([]); const [suggestionsLoading, setSuggestionsLoading] = useState(false); const [scenarios, setScenarios] = useState<any[]>(() => { try { return JSON.parse(localStorage.getItem("heatscape-scenarios") || "[]"); } catch { return []; } }); const [auditLogs, setAuditLogs] = useState<any[]>(() => { try { return JSON.parse(localStorage.getItem("heatscape-audit-logs") || "[]"); } catch { return []; } }); const city = activeCity;
  const [hybridToggles, setHybridToggles] = useState({ roofs: true, canopy: true, misting: true });
  const [hybridWeights, setHybridWeights] = useState({ roofs: 50, canopy: 30, misting: 20 });
  const [tenderMode, setTenderMode] = useState<"standard" | "composite">("standard");
  const calc = useMemo(() => { const lakhs = budget / 100000; const planA = 2.2 + lakhs * .085; const planB = 1.8 + lakhs * .06; const planC = 1.35 + lakhs * .045; let remainingBudget = budget; let totalCost = 0; const tenderItems = []; const mistingQty = remainingBudget >= 500000 ? 1 : 0; const mistingCost = mistingQty * 120000; remainingBudget -= mistingCost; totalCost += mistingCost; if (mistingQty > 0) { tenderItems.push({ name: "Misting corridor allowance", unit: "corridors", qty: mistingQty, unitRate: 120000, total: mistingCost }); } const halfRemainder = remainingBudget / 2; const roofQty = Math.floor(halfRemainder / 160); const roofCost = roofQty * 160; remainingBudget -= roofCost; totalCost += roofCost; tenderItems.push({ name: "High-albedo cool roof coating", unit: "m²", qty: roofQty, unitRate: 160, total: roofCost }); let treeQty = Math.floor(remainingBudget / 1400); if (utilities) { treeQty = Math.min(120, treeQty); } const treeCost = treeQty * 1400; remainingBudget -= treeCost; totalCost += treeCost; tenderItems.push({ name: "Native urban canopy", unit: "saplings", qty: treeQty, unitRate: 1400, total: treeCost }); return { lakhs, planA, planB, planC, tenderItems, totalCost, roofs: roofQty, trees: treeQty, aRoi: 14.5 + lakhs * .15, bRoi: 10.8 + lakhs * .06, cRoi: 12.4 + lakhs * .09 }; }, [budget, utilities]);
  const compositeCalc = useMemo(() => {
    let rawTotal = 0;
    if (hybridToggles.roofs) rawTotal += hybridWeights.roofs;
    if (hybridToggles.canopy) rawTotal += hybridWeights.canopy;
    if (hybridToggles.misting) rawTotal += hybridWeights.misting;
    let fR = hybridToggles.roofs ? hybridWeights.roofs / (rawTotal || 1) : 0;
    let fC = hybridToggles.canopy ? hybridWeights.canopy / (rawTotal || 1) : 0;
    let fM = hybridToggles.misting ? hybridWeights.misting / (rawTotal || 1) : 0;
    if (rawTotal === 0) { fR = fC = fM = 0; }
    const tenderItems = []; let remainingBudget = budget; let totalCost = 0;
    const mistingBudget = budget * fM; const mistingQty = Math.floor(mistingBudget / 120000); const mistingCost = mistingQty * 120000;
    if (mistingQty > 0) { tenderItems.push({ name: "Misting corridor allowance", unit: "corridors", qty: mistingQty, unitRate: 120000, total: mistingCost }); remainingBudget -= mistingCost; totalCost += mistingCost; }
    const roofBudget = budget * fR; const roofQty = Math.floor(roofBudget / 160); const roofCost = roofQty * 160;
    if (roofQty > 0) { tenderItems.push({ name: "High-albedo cool roof coating", unit: "m²", qty: roofQty, unitRate: 160, total: roofCost }); remainingBudget -= roofCost; totalCost += roofCost; }
    const canopyBudget = budget * fC; const canopyQty = Math.floor(canopyBudget / 1400); const canopyCost = canopyQty * 1400;
    if (canopyQty > 0) { tenderItems.push({ name: "Native urban canopy", unit: "saplings", qty: canopyQty, unitRate: 1400, total: canopyCost }); remainingBudget -= canopyCost; totalCost += canopyCost; }
    const utciDrop = (fR * 2.5 + fC * 3.8 + fM * 2.0) * 1.12;
    const co2Reduction = Math.round((fR * 120 + fC * 400 + fM * 50) * 1.15);
    const roi = (fR * 12 + fC * 8 + fM * 14) * 1.2;
    const summary = `Implementing a hybrid composite policy consisting of **${(fR*100).toFixed(0)}% Cool Roofs**, **${(fC*100).toFixed(0)}% Urban Canopy**, and **${(fM*100).toFixed(0)}% Misting Infrastructure** will result in a projected **-${utciDrop.toFixed(1)}°C UTCI Drop**, sequestering **-${co2Reduction} tons of CO2**, with a 5-year ROI of **${roi.toFixed(1)}%**.`;
    return { tenderItems, totalCost, utciDrop, co2Reduction, roi, summary, fR, fC, fM };
  }, [budget, hybridToggles, hybridWeights]);
  const chooseCity = (key: CityKey) => { const selected = cityData[key]; setCityKey(key); setQuery(key); setSuggestions([]); void resolvePlace({ display_name: `${selected.city}, ${selected.state}`, lat: String(selected.lat), lon: String(selected.lon) }); };
  const saveScenario = () => { const next = [{ id: Date.now(), city: city.city, state: city.state, zone: city.zone, lat: city.lat, lon: city.lon, temp: city.temp, surface: city.surface, utci: city.utci, budget: budget / 100000, plan: "A / Maximum Cooling", savedAt: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }) }, ...scenarios].slice(0, 8); setScenarios(next); localStorage.setItem("heatscape-scenarios", JSON.stringify(next)); setTenderMode("standard"); setTenderOpen(true); };
  const loadScenario = (scenario: any) => { setQuery(scenario.city); setBudget(Math.round(scenario.budget * 100000)); if (scenario.lat && scenario.lon) setActiveCity({ city: scenario.city, state: scenario.state || "", zone: scenario.zone || scenario.city, lat: scenario.lat, lon: scenario.lon, temp: scenario.temp ?? city.temp, surface: scenario.surface ?? city.surface, utci: scenario.utci ?? city.utci }); setSavedOpen(false); toast.success("Scenario restored", { description: `${scenario.city} / ₹${scenario.budget.toFixed(1)}L` }); };
  const resolvePlace = async (place: any) => { const fallback = cityKeys.find((key) => key.toLowerCase() === String(place.display_name || "").split(",")[0].trim().toLowerCase()) ? cityData[String(place.display_name).split(",")[0].trim() as CityKey] : cityData.Chennai; const lat = Number(place.lat); const lon = Number(place.lon); try { const weatherResponse = await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,apparent_temperature,relative_humidity_2m`); if (!weatherResponse.ok) throw new Error("Weather feed unavailable"); const current = (await weatherResponse.json()).current ?? {}; const temp = Number(current.temperature_2m ?? fallback.temp); const resolved: City = { city: String(place.display_name || "Selected location").split(",")[0], state: String(place.display_name || "").split(",")[1]?.trim() || fallback.state, lat, lon, temp, surface: Number((temp + 13.4).toFixed(1)), utci: Number(current.apparent_temperature ?? fallback.utci), humidity: Number(current.relative_humidity_2m ?? 63), zone: String(place.display_name || fallback.zone) }; setActiveCity(resolved); setQuery(resolved.city); setSuggestions([]); toast.success("Live micro-zone telemetry synced", { description: `${resolved.city} / Nominatim + Open-Meteo` }); } catch (error) { const payload = { ambientTemperature: 35.5, surfaceTemperature: 49.1, pedestrianHeatStressUTCI: 39.8, primaryHeatDrivers: ["Dense asphalt concentration", "Lack of reflective surfaces", "Severe canopy deficit"], isFallback: true }; const resolved: City = { ...fallback, city: String(place.display_name || fallback.city).split(",")[0], lat, lon, zone: String(place.display_name || fallback.zone), temp: payload.ambientTemperature, surface: payload.surfaceTemperature, utci: payload.pedestrianHeatStressUTCI, primaryHeatDrivers: payload.primaryHeatDrivers, isFallback: payload.isFallback }; setActiveCity(resolved); setQuery(resolved.city); setSuggestions([]); const newLog = { id: Date.now(), time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" }), message: "API failure. Graceful degradation to deterministic climate model.", payload }; const nextLogs = [newLog, ...auditLogs].slice(0, 50); setAuditLogs(nextLogs); localStorage.setItem("heatscape-audit-logs", JSON.stringify(nextLogs)); toast.info("Offline-safe fallback loaded", { description: "Live weather was unavailable; using calibrated fallback telemetry." }); } };
  useEffect(() => { const normalized = query.trim(); if (normalized.length < 3 || cityKeys.some((key) => key.toLowerCase() === normalized.toLowerCase())) { setSuggestions([]); return; } const controller = new AbortController(); const timer = window.setTimeout(async () => { setSuggestionsLoading(true); try { const response = await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(normalized)}&limit=5`, { headers: { Accept: "application/json" }, signal: controller.signal }); if (!response.ok) throw new Error("Autocomplete unavailable"); setSuggestions(await response.json()); } catch (error) { if ((error as Error).name !== "AbortError") setSuggestions([]); } finally { setSuggestionsLoading(false); } }, 300); return () => { window.clearTimeout(timer); controller.abort(); }; }, [query]);
  const searchCity = async () => { const normalized = query.trim(); const match = cityKeys.find((key) => key.toLowerCase() === normalized.toLowerCase()); if (match) { chooseCity(match); return; } try { const response = await fetch(`https://nominatim.openstreetmap.org/search?format=json&q=${encodeURIComponent(normalized)}&limit=1`, { headers: { Accept: "application/json" } }); if (!response.ok) throw new Error("Geocoder unavailable"); const places = await response.json(); if (!places[0]) throw new Error("City not found"); await resolvePlace(places[0]); } catch { if (match) chooseCity(match); else toast.error("Location lookup unavailable", { description: "Try a more specific place name." }); } };
  const selectSuggestion = (place: any) => { void resolvePlace(place); };
  useEffect(() => { const initial = cityData.Chennai; void resolvePlace({ display_name: `${initial.city}, ${initial.state}`, lat: String(initial.lat), lon: String(initial.lon) }); }, []);
  return <div className="light-app"><AnimatePresence>{loading && <QuenchLoader onDone={() => setLoading(false)} />}</AnimatePresence><header className="light-nav"><div className="light-brand"><span>HS</span><div><b>HEATSCAPE</b><small>URBAN HEAT REDUCTION PLANNER</small></div></div><nav><button className={activeTab === "planner" ? "active" : ""} onClick={() => setActiveTab("planner")}>Planner</button><button className={activeTab === "hotspots" ? "active" : ""} onClick={() => setActiveTab("hotspots")}>Hotspots</button><button className={activeTab === "interventions" ? "active" : ""} onClick={() => setActiveTab("interventions")}>Interventions</button></nav><div className="nav-tools"><button className="saved-nav" onClick={() => setSavedOpen(true)}><History size={14} /> SAVED <b>{scenarios.length}</b></button><button className="saved-nav" onClick={() => setAuditOpen(true)}><ShieldCheck size={14} /> AUDIT LOG <b>{auditLogs.length}</b></button><span><i className="live-mark" /> LIVE MODEL</span><CircleHelp size={16} /><b>AR</b></div></header>{activeTab === "planner" ? <main className="light-main"><div className="masthead"><div><Kicker>MUNICIPAL CONTROL CENTER / 07 SEP 2026</Kicker><h1>Cool the city.<br /><em>Precisely.</em></h1><p>Real-time thermodynamic modeling paired with deterministic capital optimization for municipal planners.</p></div><div className="masthead-note"><span>01</span><b>SELECT A CITY<br />MODEL THE INTERVENTION</b><ArrowUpRight size={16} /></div></div>
    <Card className="command-light"><div className="light-section-head"><Kicker>COMMAND CENTER</Kicker><small>INPUT / 01</small></div><div className="command-light-grid"><div className="search-wrapper"><label>TARGET URBAN ZONE</label><div className="light-search"><MapPin size={17} /><input value={query} onChange={(e) => setQuery(e.target.value)} onKeyDown={(e) => e.key === "Enter" && searchCity()} /><button onClick={searchCity}><Search size={16} /></button></div>{suggestions.length > 0 && <div className="search-suggestions">{suggestions.map((place) => <button key={`${place.place_id}-${place.lat}`} onClick={() => selectSuggestion(place)}><MapPin size={13} /><span><b>{String(place.display_name).split(",")[0]}</b><small>{String(place.display_name).split(",").slice(1, 3).join(",").trim()}</small></span></button>)}</div>}{suggestionsLoading && <div className="search-loading">SEARCHING NOMINATIM…</div>}<div className="city-chips">{cityKeys.map((key) => <button key={key} className={key === cityKey ? "selected" : ""} onClick={() => chooseCity(key)}>{key}</button>)}</div></div><div className="city-readout"><div><MapPin size={16} /> {city.city}, {city.state} <span><Check size={11} /> VERIFIED</span></div><small>LAT <b>{city.lat.toFixed(4)}° N</b> &nbsp; LON <b>{city.lon.toFixed(4)}° E</b></small></div></div></Card>
    <div className="light-workspace"><Card className="globe-light"><div className="light-section-head"><Kicker>SPATIAL HEAT LAYER</Kicker><button className={`risk-toggle ${showRisk ? "active" : ""}`} onClick={() => setShowRisk(!showRisk)}><Layers3 size={13} /> {showRisk ? "RISK ZONES ON" : "SHOW RISK ZONES"}</button></div><StreetMap city={city} onPick={chooseCity} showRisk={showRisk} /></Card><Card className="board-light"><div className="light-section-head"><Kicker>PHYSICAL CONTROL BOARD</Kicker><small>INPUT / 02</small></div><label>DEPLOYMENT BUDGET</label><div className="budget-light">₹<Ticker value={budget / 100000} suffix="L" /></div><div className="physical-range"><input type="range" min="500000" max="5000000" step="50000" value={budget} onChange={(e) => setBudget(Number(e.target.value))} /><div style={{ width: `${((budget - 500000) / 4500000) * 100}%` }} /></div><div className="range-copy"><span>₹5.0L</span><span>₹50.0L</span></div><div className="light-switches"><Toggle label="Underground utilities" hint="Root barrier safety active" checked={utilities} onChange={() => setUtilities(!utilities)} icon={<ShieldCheck size={16} />} /><Toggle label="Heavy transit" hint="Transit-grade asphalt logic" checked={transit} onChange={() => setTransit(!transit)} icon={<Wind size={16} />} /></div><div className="solver-note"><ShieldCheck size={15} /> Physics-validated solver / ISO 7730 compliant</div></Card></div>
    <Card className="telemetry-light"><div className="light-section-head"><Kicker>TELEMETRY DASHBOARD / {city.zone}</Kicker><strong><i className="live-mark" /> LIVE WEATHER FEED</strong></div><div className="light-metrics"><div><span>AMBIENT TEMPERATURE</span><strong><Ticker value={city.temp} suffix="°C" /></strong><small>BASELINE SIGNAL</small></div><div><span>SURFACE TEMPERATURE</span><strong className="terracotta"><Ticker value={city.surface} suffix="°C" /></strong><small>THERMAL HOTSPOT</small></div><div><span>UTCI / PEDESTRIAN STRESS</span><strong className="lapis"><Ticker value={city.utci} suffix="°C" /></strong><small>{city.utci >= 45 ? "EXTREME DANGER" : city.utci >= 32 ? "VERY STRONG STRESS" : "MODERATE STRESS"}</small></div></div><div className="metric-foot"><span><Sun size={14} /> SOLAR 812 W/m²</span><span><Droplets size={14} /> HUMIDITY {city.humidity ?? 63}%</span><span><Waves size={14} /> CONFIDENCE 98.4%</span></div></Card>
    <div className="optimizer-title"><div><Kicker>OPTIMIZER ENGINE / LIVE RESPONSE</Kicker><h2>Capital plans that cool on contact.</h2></div><button className="compare-button" onClick={() => setCompareOpen(true)}><GitCompareArrows size={15} /> COMPARE PLAN A + B</button></div><div className="light-plans"><Plan featured letter="A" title="Maximum Cooling" subtitle="60% cool roofs / 40% urban canopy" color="#0284c7" drop={calc.planA} roi={calc.aRoi} payback={3.8 - calc.lakhs * .025} emissions={270 + calc.lakhs * 13} icon={<Droplets size={20} />} /><Plan letter="B" title="Eco-Forestry" subtitle="Miyawaki planting / permeable bioswales" color="#15803d" drop={calc.planB} roi={calc.bRoi} payback={4.5} emissions={400 + calc.lakhs * 15} icon={<Trees size={20} />} /><Plan letter="C" title="Rapid Tactical" subtitle="Shade sails / reflective albedo paint" color="#b45309" drop={calc.planC} roi={12.4 + calc.lakhs * .09} payback={2.8} emissions={200 + calc.lakhs * 8} icon={<Zap size={20} />} /></div>
    <Card className="paper-card composite-matrix" style={{ marginTop: "24px", padding: "24px" } as React.CSSProperties}>
      <div className="matrix-head" style={{ marginBottom: "20px" }}>
        <Kicker>SYNERGY ENGINE</Kicker>
        <h2 style={{ fontSize: "20px", fontWeight: 800, letterSpacing: "-0.03em" }}>Advanced Composite Policy Matrix (A + B + C Blend)</h2>
      </div>
      <div className="matrix-controls" style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "20px", marginBottom: "24px" }}>
        <div className="matrix-control">
          <label style={{ display: "flex", alignItems: "center", gap: "8px", fontWeight: "bold", marginBottom: "8px" }}>
            <input type="checkbox" checked={hybridToggles.roofs} onChange={(e) => setHybridToggles(t => ({...t, roofs: e.target.checked}))} />
            High-Albedo Cool Roofs
          </label>
          <input type="range" min="0" max="100" value={hybridWeights.roofs} disabled={!hybridToggles.roofs} onChange={(e) => setHybridWeights(w => ({...w, roofs: Number(e.target.value)}))} style={{ width: "100%", accentColor: "var(--lapis)" }} />
          <div style={{ textAlign: "right", fontSize: "12px", color: "var(--stone)" }}>{(compositeCalc.fR * 100).toFixed(0)}% Allocation</div>
        </div>
        <div className="matrix-control">
          <label style={{ display: "flex", alignItems: "center", gap: "8px", fontWeight: "bold", marginBottom: "8px" }}>
            <input type="checkbox" checked={hybridToggles.canopy} onChange={(e) => setHybridToggles(t => ({...t, canopy: e.target.checked}))} />
            Native Urban Canopy
          </label>
          <input type="range" min="0" max="100" value={hybridWeights.canopy} disabled={!hybridToggles.canopy} onChange={(e) => setHybridWeights(w => ({...w, canopy: Number(e.target.value)}))} style={{ width: "100%", accentColor: "var(--sage)" }} />
          <div style={{ textAlign: "right", fontSize: "12px", color: "var(--stone)" }}>{(compositeCalc.fC * 100).toFixed(0)}% Allocation</div>
        </div>
        <div className="matrix-control">
          <label style={{ display: "flex", alignItems: "center", gap: "8px", fontWeight: "bold", marginBottom: "8px" }}>
            <input type="checkbox" checked={hybridToggles.misting} onChange={(e) => setHybridToggles(t => ({...t, misting: e.target.checked}))} />
            Misting Corridors / Bioswales
          </label>
          <input type="range" min="0" max="100" value={hybridWeights.misting} disabled={!hybridToggles.misting} onChange={(e) => setHybridWeights(w => ({...w, misting: Number(e.target.value)}))} style={{ width: "100%", accentColor: "var(--terracotta)" }} />
          <div style={{ textAlign: "right", fontSize: "12px", color: "var(--stone)" }}>{(compositeCalc.fM * 100).toFixed(0)}% Allocation</div>
        </div>
      </div>
      <div className="matrix-summary" style={{ background: "rgba(0,0,0,0.03)", padding: "16px", borderRadius: "8px", marginBottom: "20px" }}>
        <p style={{ margin: 0, lineHeight: 1.6 }} dangerouslySetInnerHTML={{ __html: compositeCalc.summary.replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>') }}></p>
      </div>
      <button className="export-composite-btn" onClick={() => { setTenderMode("composite"); setTenderOpen(true); }} style={{ width: "100%", padding: "14px", background: "var(--carbon)", color: "white", borderRadius: "8px", fontWeight: "bold", display: "flex", justifyContent: "center", alignItems: "center", gap: "8px", cursor: "pointer", border: "none" }}>
        Export Composite Municipal Tender (A+B+C) <ArrowUpRight size={16} />
      </button>
    </Card>
    <div className="light-action"><span><i className="live-mark" /> PROJECTED IMPACT <b>−{calc.planA.toFixed(1)}°C UTCI / {calc.trees} canopy units</b></span><button onClick={saveScenario}>EXPORT MUNICIPAL TENDER (BoQ) <ArrowUpRight size={16} /></button></div></main> : activeTab === "hotspots" ? <HotspotsView city={city} /> : <InterventionsView />}<footer className="light-footer"><span>HEATSCAPE / 2026</span><span>Urban heat decisions, made tangible.</span><span>DATA SOURCES: LANDSAT · ERA5 · OPEN-METEO</span></footer><AnimatePresence>{compareOpen && <ComparisonModal calc={calc} city={city} onClose={() => setCompareOpen(false)} />}{savedOpen && <SavedDrawer scenarios={scenarios} onClose={() => setSavedOpen(false)} onLoad={loadScenario} />}{auditOpen && <AuditDrawer logs={auditLogs} onClose={() => setAuditOpen(false)} />}</AnimatePresence>
    <AnimatePresence>{tenderOpen && <TenderModal city={city} budget={budget} calc={tenderMode === "composite" ? compositeCalc : calc} mode={tenderMode} onClose={() => setTenderOpen(false)} />}</AnimatePresence></div>;
}

function TenderModal({ city, budget, calc, mode, onClose }: { city: City; budget: number; calc: any; mode: "standard" | "composite"; onClose: () => void }) { return <motion.div className="paper-modal-wrap" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.div className="tender-paper" initial={{ y: 20, scale: .98 }} animate={{ y: 0, scale: 1 }}><button className="paper-close" onClick={onClose}><X size={17} /></button><div className="paper-kicker">MUNICIPAL CORPORATION CAPITAL WORKS DIVISION</div><h2>Urban Heat Mitigation Tender</h2><p className="paper-sub">Schedule of Rates &amp; Bill of Quantities / {city.city}, {city.state}</p><div className="paper-meta"><span>PROJECT ZONE <b>{city.zone}</b></span><span>CAPITAL CEILING <b>₹{(budget / 100000).toFixed(1)}L</b></span><span>{mode === "composite" ? "COMPOSITE TARGET" : "PLAN A UTCI TARGET"} <b>−{(calc.planA || calc.utciDrop).toFixed(1)}°C</b></span></div><table><thead><tr><th>ITEM</th><th>QUANTITY</th><th>UNIT RATE</th><th>TOTAL</th></tr></thead><tbody>{calc.tenderItems.map((item: any, i: number) => <tr key={i}><td>{item.name}</td><td>{item.qty.toLocaleString()} {item.unit}</td><td>₹{item.unitRate.toLocaleString()} / unit</td><td>₹{item.total.toLocaleString()}</td></tr>)}<tr style={{ borderTop: "2px solid #ddd9d0", fontWeight: "bold" }}><td colSpan={3}>TOTAL COST</td><td>₹{calc.totalCost.toLocaleString()}</td></tr></tbody></table><div className="approval"><div><Check size={15} /> Stage 1: Climate Budget Verified</div><div className="pending"><span /> Stage 2: Pending Tender Board Audit</div></div><div className="paper-actions"><button onClick={onClose}>Close</button><button className="print-btn" onClick={() => window.print()}><Printer size={15} /> Print / Save as PDF <ArrowUpRight size={14} /></button></div></motion.div></motion.div>; }
